name: docs
on:
  pull_request:
    branches: ['main']
permissions: {}
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Setup python 3.14
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: '3.14'
        cache: 'pip'
    - name: Install deps
      run: pip install -r requirements-docs.txt
    - name: Build docs
      run: sphinx-build source apidocs -bhtml
